Configurable CabSignal activation with cabin activation
Milek7/maszyna pull request #17
Opened 2022-04-29 20:59 UTC by Xoov

2022-05-29 21:50 UTC, Milek7 requested changes
Instead of this, couldn't we just cut pwr signal while cab is not active?

2022-05-29 21:50 UTC, Milek7 commented on McZapkie/Mover.cpp
> +	bool is_powered = !power && pwr;
confusing var name (`just_powered_on`?)

2022-05-29 21:50 UTC, Milek7 commented on McZapkie/Mover.cpp
> +	bool is_cabactived = CabDependent && (cabactive != cab);
confusing var name (`just_activated`?)

2022-05-29 21:50 UTC, Milek7 commented on McZapkie/Mover.cpp
> +		if (!DebugModeFlag)
I think it's better to add condition to line 139 instead.

2022-06-04 20:10 UTC, Xoov commented
> Instead of this, couldn't we just cut pwr signal while cab is not active?

Yes. However it will be changed when refactoring that code and adding new features (cutting off, true multi-traction support, emergency loop).

2022-06-23 20:39 UTC, merged